/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e2e4",
        "tertiary-container": "#2170e4",
        "surface": "#f8f9fb",
        "primary-container": "#00873a",
        "on-secondary": "#ffffff",
        "on-background": "#191c1e",
        "on-primary-fixed": "#002109",
        "tertiary": "#0058be",
        "on-error": "#ffffff",
        "secondary-container": "#dae2fd",
        "inverse-on-surface": "#f0f1f3",
        "on-tertiary-container": "#fefcff",
        "on-tertiary-fixed-variant": "#004395",
        "on-primary-container": "#f7fff2",
        "secondary": "#565e74",
        "on-primary-fixed-variant": "#005320",
        "on-surface-variant": "#3e4a3d",
        "secondary-fixed": "#dae2fd",
        "primary-fixed-dim": "#62df7d",
        "surface-tint": "#006e2d",
        "on-primary": "#ffffff",
        "primary": "#006b2c",
        "inverse-primary": "#62df7d",
        "on-error-container": "#93000a",
        "background": "#f8f9fb",
        "on-secondary-container": "#5c647a",
        "surface-container-highest": "#e1e2e4",
        "surface-bright": "#f8f9fb",
        "inverse-surface": "#2e3132",
        "error": "#ba1a1a",
        "surface-container": "#edeef0",
        "outline-variant": "#bdcaba",
        "surface-container-low": "#f3f4f6",
        "surface-container-high": "#e7e8ea",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#bec6e0",
        "tertiary-fixed-dim": "#adc6ff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#3f465c",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#001a42",
        "on-secondary-fixed": "#131b2e",
        "outline": "#6e7b6c",
        "primary-fixed": "#7ffc97",
        "surface-dim": "#d9dadc",
        "tertiary-fixed": "#d8e2ff"
      },
      spacing: {
        "base": "4px",
        "gutter": "16px",
        "container-padding": "24px",
        "sidebar-width": "260px",
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        'data-tabular': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'data-tabular': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
