// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddSupplierExpense(arg1:number,arg2:number,arg3:string,arg4:string):Promise<models.SupplierExpense>;

export function CreateService(arg1:models.MedicalService):Promise<models.MedicalService>;

export function CreateSupplier(arg1:string,arg2:number,arg3:number):Promise<models.Supplier>;

export function CreateUser(arg1:models.User):Promise<number>;

export function DeleteService(arg1:number):Promise<void>;

export function DeleteSupplier(arg1:number):Promise<void>;

export function DeleteSupplierExpense(arg1:number):Promise<void>;

export function ExportAnnualExcel(arg1:number):Promise<string>;

export function ExportDailyPDF(arg1:string):Promise<string>;

export function GenerateDecharge(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<string>;

export function GenerateDechargeHonoraire(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<string>;

export function GetAllSuppliers():Promise<Array<models.Supplier>>;

export function GetAnnualReport(arg1:number):Promise<models.AnnualReport>;

export function GetCurrentUser():Promise<models.User>;

export function GetDailyEntry(arg1:string):Promise<models.DailyEntryWithExpenses>;

export function GetDechargeTemplateStatus():Promise<Record<string, boolean>>;

export function GetInvestments(arg1:number,arg2:number):Promise<Array<models.Investment>>;

export function GetMonthlyHonoraires(arg1:number,arg2:number):Promise<Array<models.MonthlyHonoraire>>;

export function GetMonthlyOffres(arg1:number,arg2:number):Promise<Array<models.MonthlyOffre>>;

export function GetMonthlyReport(arg1:number,arg2:number):Promise<models.MonthlyReport>;

export function GetServices():Promise<Array<models.MedicalService>>;

export function GetSupplierBudgetSummary(arg1:number):Promise<Array<models.SupplierBudgetSummary>>;

export function GetSupplierExpenses(arg1:number):Promise<Array<models.SupplierExpense>>;

export function GetSuppliers(arg1:number):Promise<Array<models.Supplier>>;

export function GetWeekHistory(arg1:string):Promise<Array<models.DayHistoryRow>>;

export function GetYearSettings(arg1:number):Promise<models.YearSettings>;

export function ImportTemplate(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<models.User>;

export function Logout():Promise<void>;

export function OpenDoc(arg1:string):Promise<void>;

export function SaveAttachment(arg1:string,arg2:string):Promise<string>;

export function SaveDailyEntry(arg1:string,arg2:Array<models.DailyServiceValue>,arg3:Array<models.DailyExpense>):Promise<void>;

export function SaveInvestments(arg1:number,arg2:number,arg3:Array<models.Investment>):Promise<void>;

export function SaveMonthlyHonoraires(arg1:number,arg2:number,arg3:Array<models.MonthlyHonoraire>):Promise<void>;

export function SaveMonthlyOffres(arg1:number,arg2:number,arg3:Array<models.MonthlyOffre>):Promise<void>;

export function SelectFile(arg1:string):Promise<string>;

export function SetInitialBalance(arg1:number,arg2:number):Promise<void>;

export function UpdateAdminProfile(arg1:models.User):Promise<models.User>;

export function UpdatePassword(arg1:number,arg2:string):Promise<void>;

export function UpdateService(arg1:models.MedicalService):Promise<models.MedicalService>;

export function UpdateSupplier(arg1:number,arg2:string,arg3:number,arg4:number):Promise<models.Supplier>;
