// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateUser(arg1:models.User):Promise<number>;

export function ExportAnnualExcel(arg1:number):Promise<string>;

export function GetAnnualReport(arg1:number):Promise<models.AnnualReport>;

export function GetCurrentUser():Promise<models.User>;

export function GetDailyEntry(arg1:string):Promise<models.DailyEntryWithExpenses>;

export function GetInvestments(arg1:number,arg2:number):Promise<Array<models.Investment>>;

export function GetMonthlyHonoraires(arg1:number,arg2:number):Promise<Array<models.MonthlyHonoraire>>;

export function GetMonthlyReport(arg1:number,arg2:number):Promise<models.MonthlyReport>;

export function GetWeekHistory(arg1:string):Promise<Array<models.DayHistoryRow>>;

export function GetYearSettings(arg1:number):Promise<models.YearSettings>;

export function Login(arg1:string,arg2:string):Promise<models.User>;

export function Logout():Promise<void>;

export function OpenDoc(arg1:string):Promise<void>;

export function SaveDailyEntry(arg1:string,arg2:models.DailyEntry,arg3:Array<models.DailyExpense>):Promise<void>;

export function SaveInvestments(arg1:number,arg2:number,arg3:Array<models.Investment>):Promise<void>;

export function SaveMonthlyHonoraires(arg1:number,arg2:number,arg3:Array<models.MonthlyHonoraire>):Promise<void>;

export function SelectFile(arg1:string):Promise<string>;

export function SetInitialBalance(arg1:number,arg2:number):Promise<void>;

export function UpdateAdminProfile(arg1:models.User):Promise<models.User>;

export function UpdatePassword(arg1:number,arg2:string):Promise<void>;
