// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSupplierExpense(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSupplierExpense'](arg1, arg2, arg3, arg4);
}

export function CreateService(arg1) {
  return window['go']['main']['App']['CreateService'](arg1);
}

export function CreateSupplier(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSupplier'](arg1, arg2, arg3);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteService(arg1) {
  return window['go']['main']['App']['DeleteService'](arg1);
}

export function DeleteSupplier(arg1) {
  return window['go']['main']['App']['DeleteSupplier'](arg1);
}

export function DeleteSupplierExpense(arg1) {
  return window['go']['main']['App']['DeleteSupplierExpense'](arg1);
}

export function ExportAnnualExcel(arg1) {
  return window['go']['main']['App']['ExportAnnualExcel'](arg1);
}

export function ExportDailyPDF(arg1) {
  return window['go']['main']['App']['ExportDailyPDF'](arg1);
}

export function GenerateDecharge(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateDecharge'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateDechargeHonoraire(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GenerateDechargeHonoraire'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAllSuppliers() {
  return window['go']['main']['App']['GetAllSuppliers']();
}

export function GetAnnualReport(arg1) {
  return window['go']['main']['App']['GetAnnualReport'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDailyEntry(arg1) {
  return window['go']['main']['App']['GetDailyEntry'](arg1);
}

export function GetDechargeTemplateStatus() {
  return window['go']['main']['App']['GetDechargeTemplateStatus']();
}

export function GetInvestments(arg1, arg2) {
  return window['go']['main']['App']['GetInvestments'](arg1, arg2);
}

export function GetMonthlyHonoraires(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyHonoraires'](arg1, arg2);
}

export function GetMonthlyOffres(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyOffres'](arg1, arg2);
}

export function GetMonthlyReport(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyReport'](arg1, arg2);
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetSupplierBudgetSummary(arg1) {
  return window['go']['main']['App']['GetSupplierBudgetSummary'](arg1);
}

export function GetSupplierExpenses(arg1) {
  return window['go']['main']['App']['GetSupplierExpenses'](arg1);
}

export function GetSuppliers(arg1) {
  return window['go']['main']['App']['GetSuppliers'](arg1);
}

export function GetWeekHistory(arg1) {
  return window['go']['main']['App']['GetWeekHistory'](arg1);
}

export function GetYearSettings(arg1) {
  return window['go']['main']['App']['GetYearSettings'](arg1);
}

export function ImportTemplate(arg1) {
  return window['go']['main']['App']['ImportTemplate'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenDoc(arg1) {
  return window['go']['main']['App']['OpenDoc'](arg1);
}

export function SaveAttachment(arg1, arg2) {
  return window['go']['main']['App']['SaveAttachment'](arg1, arg2);
}

export function SaveDailyEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDailyEntry'](arg1, arg2, arg3);
}

export function SaveInvestments(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveInvestments'](arg1, arg2, arg3);
}

export function SaveMonthlyHonoraires(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMonthlyHonoraires'](arg1, arg2, arg3);
}

export function SaveMonthlyOffres(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMonthlyOffres'](arg1, arg2, arg3);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SetInitialBalance(arg1, arg2) {
  return window['go']['main']['App']['SetInitialBalance'](arg1, arg2);
}

export function UpdateAdminProfile(arg1) {
  return window['go']['main']['App']['UpdateAdminProfile'](arg1);
}

export function UpdatePassword(arg1, arg2) {
  return window['go']['main']['App']['UpdatePassword'](arg1, arg2);
}

export function UpdateService(arg1) {
  return window['go']['main']['App']['UpdateService'](arg1);
}

export function UpdateSupplier(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSupplier'](arg1, arg2, arg3, arg4);
}
