// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function ExportAnnualExcel(arg1) {
  return window['go']['main']['App']['ExportAnnualExcel'](arg1);
}

export function GetAnnualReport(arg1) {
  return window['go']['main']['App']['GetAnnualReport'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDailyEntry(arg1) {
  return window['go']['main']['App']['GetDailyEntry'](arg1);
}

export function GetInvestments(arg1, arg2) {
  return window['go']['main']['App']['GetInvestments'](arg1, arg2);
}

export function GetMonthlyHonoraires(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyHonoraires'](arg1, arg2);
}

export function GetMonthlyReport(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyReport'](arg1, arg2);
}

export function GetWeekHistory(arg1) {
  return window['go']['main']['App']['GetWeekHistory'](arg1);
}

export function GetYearSettings(arg1) {
  return window['go']['main']['App']['GetYearSettings'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenDoc(arg1) {
  return window['go']['main']['App']['OpenDoc'](arg1);
}

export function SaveDailyEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDailyEntry'](arg1, arg2, arg3);
}

export function SaveInvestments(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveInvestments'](arg1, arg2, arg3);
}

export function SaveMonthlyHonoraires(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMonthlyHonoraires'](arg1, arg2, arg3);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SetInitialBalance(arg1, arg2) {
  return window['go']['main']['App']['SetInitialBalance'](arg1, arg2);
}

export function UpdateAdminProfile(arg1) {
  return window['go']['main']['App']['UpdateAdminProfile'](arg1);
}

export function UpdatePassword(arg1, arg2) {
  return window['go']['main']['App']['UpdatePassword'](arg1, arg2);
}
